name: Java CI with Gradle

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TARGET_VERSION: "1.20.4"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '21'
    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build only version 1.20.4
      if: env.TARGET_VERSION == '1.20.4'
      run: ./gradlew build -Ptarget_subproject=${{ env.TARGET_VERSION }}

    - name: Run tests
      if: env.TARGET_VERSION == '1.20.4'
      run: ./gradlew test -Ptarget_subproject=${{ env.TARGET_VERSION }}
